TRACK_WORDS = [
"Acute myeloid leukaemia",
"Acute pancreatitis",
"Allergic rhinitis",
"Allergies",
"Alzheimer",
"Anaphylaxis",
"Angioedema",
"Ankylosing spondylitis",
"Anorexia nervosa",
"Anxiety",
"Appendicitis",
"Arthritis",
"Asbestosis",
"Asthma",
"Atopic eczema",
"Autistic spectrum disorder (ASD)",
"Bacterial vaginosis",
"Benign prostate enlargement",
"Bile duct cancer (cholangiocarcinoma)",
"Binge eating",
"Bipolar disorder",
"Bladder cancer",
"Blood poisoning (sepsis)",
"Bone cancer",
"Bowel cancer",
"Bowel incontinence",
"Bowel polyps",
"Brain stem death",
"Brain tumours",
"Breast cancer",
"Bronchiectasis",
"Bronchitis",
"Bulimia",
"Bunion",
"Catarrh",
"Cellulitis",
"Cervical cancer",
"Chest infection",
"Chest pain",
"Chickenpox",
"Chilblains",
"Chronic fatigue syndrome",
"Chronic kidney disease",
"Chronic lymphocytic leukaemia",
"Chronic myeloid leukaemia",
"Chronic obstructive pulmonary disease",
"Chronic pancreatitis",
"Cirrhosis",
"Clostridium difficile",
"Coeliac disease",
"Cold sore",
"Congenital heart disease",
"Conjunctivitis",
"Constipation",
"Cough",
"Crohn's disease",
"Croup",
"Cystic fibrosis",
"Cystitis",
"Deafblindness",
"Deep vein thrombosis",
"Dehydration",
"Dementia",
"Dementia with Lewy bodies",
"Dental abscess",
"Depression",
"Dermatitis herpetiformis",
"Diabetes",
"Diarrhoea",
"Discoid eczema",
"Diverticular disease",
"Dizziness (Lightheadedness)",
"Down's syndrome",
"Dry mouth",
"Dysphagia (swallowing problems)",
"Dystonia",
"Earache",
"Earwax build-up",
"Ebola virus disease",
"Ectopic pregnancy",
"Endometriosis",
"Epilepsy",
"Erectile dysfunction (impotence)",
"Escherichia coli",
"Ewing sarcoma",
"Eye cancer",
"Febrile seizures",
"Fibroids",
"Fibromyalgia",
"Flatulence",
"Flu",
"Foetal alcohol syndrome",
"Food poisoning",
"Fungal nail infection",
"Gallbladder cancer",
"Gallstones",
"Ganglion cyst",
"Gastroenteritis",
"Gastro-oesophageal reflux disease (GORD)",
"Genital herpes",
"Genital warts",
"Germ cell tumours",
"Glandular fever",
"Gout",
"Gum disease",
"Haemorrhoids (piles)",
"Hairy cell leukaemia",
"Hay fever",
"Head lice",
"Headaches",
"Hearing loss",
"Heart failure",
"Hepatitis A",
"Hepatitis B",
"Hepatitis C",
"Hiatus hernia",
"High cholesterol",
"HIV",
"Hodgkin lymphoma",
"Hodgkin lymphoma: Children",
"Hodgkin lymphoma",
"Huntington's disease",
"Hyperglycaemia (high blood sugar)",
"Hyperhidrosis",
"Hypoglycaemia (low blood sugar)",
"Idiopathic pulmonary fibrosis",
"Impetigo",
"Indigestion",
"Ingrown toenail",
"Inherited heart conditions",
"Insomnia",
"Iron deficiency anaemia",
"Irritable bowel syndrome (IBS)",
"Irritable hip",
"Itching",
"Itchy bottom",
"Kaposi's sarcoma",
"Kidney cancer",
"Kidney infection",
"Kidney stones",
"Labyrinthitis",
"Lactose intolerance",
"Langerhans cell histiocytosis",
"Laryngeal (larynx) cancer",
"Laryngitis",
"Leg cramps",
"Lichen planus",
"Liver cancer",
"Liver disease",
"Liver tumours",
"Loss of libido",
"Lung cancer",
"Lupus",
"Lyme disease",
"Lymphoedema",
"Malaria",
"Malignant brain tumour (cancerous)",
"Malnutrition",
"Measles",
"Meningitis",
"Menopause",
"Mesothelioma",
"Middle ear infection (otitis media)",
"Migraine",
"Miscarriage",
"Motor neurone disease (MND)",
"Mouth cancer",
"Mouth ulcer",
"Multiple myeloma",
"Multiple sclerosis (MS)",
"Mumps",
"Meniere's disease",
"Sinus cancer",
"Nasopharyngeal cancer",
"Neuroblastoma",
"Neuroendocrine tumours",
"Non-alcoholic fatty liver disease (NAFLD)",
"Non-Hodgkin lymphoma",
"Norovirus",
"Nosebleed",
"Obesity",
"Obsessive compulsive disorder (OCD)",
"Obstructive sleep apnoea",
"Oesophageal cancer",
"Oral thrush",
"Osteoarthritis",
"Osteoporosis",
"Osteosarcoma",
"Otitis externa",
"Ovarian cancer",
"Ovarian cyst",
"Overactive thyroid",
"Paget's disease of the nipple",
"Pancreatic cancer",
"Panic disorder",
"Parkinson's disease",
"Pelvic organ prolapse",
"Penile cancer",
"Peripheral neuropathy",
"Personality disorder",
"Pleurisy",
"Pneumonia",
"Polymyalgia rheumatica",
"Post-traumatic stress disorder (PTSD)",
"Postnatal depression",
"Pressure ulcers",
"Prostate cancer",
"Psoriasis",
"Psoriatic arthritis",
"Psychosis",
"Rare tumours",
"Raynaud's phenomenon",
"Reactive arthritis",
"Restless legs syndrome",
"Retinoblastoma",
"Rhabdomyosarcoma",
"Rheumatoid arthritis",
"Ringworm",
"Rosacea",
"Scabies",
"Scarlet fever",
"Schizophrenia",
"Scoliosis",
"Septic shock",
"Sexually transmitted infections (STIs)",
"Shingles",
"Shortness of breath",
"Sickle cell disease",
"Sinusitis",
"Sjogren's syndrome",
"Skin cancer (melanoma)",
"Skin cancer (non-melanoma)",
"Slapped cheek syndrome",
"Soft tissue sarcomas",
"Sore throat",
"Spleen problems",
"spleen removal",
"Stillbirth",
"Stomach ache",
"abdominal pain",
"Stomach cancer",
"Stomach ulcer",
"Stress",
"anxiety",
"low mood",
"Stroke",
"Sudden infant death syndrome (SIDS)",
"Suicide",
"Sunburn",
"Swollen glands",
"Testicular cancer",
"Testicular lumps",
"swellings",
"Thirst",
"Threadworms",
"Thrush",
"Thyroid cancer",
"Tinnitus",
"Tonsillitis",
"Tooth decay",
"Toothache",
"Transient ischaemic attack (TIA)",
"Trigeminal neuralgia",
"Tuberculosis (TB)",
"Ulcerative colitis",
"Underactive thyroid",
"Urinary incontinence",
"Urinary tract infection (UTI)",
"Urticaria (hives)",
"Vaginal cancer",
"Vaginal thrush",
"Varicose eczema",
"Varicose veins",
"Venous leg ulcer",
"Vertigo",
"folate deficiency anaemia",
"Vomiting",
"Vulval cancer",
"Warts",
"verrucas",
"Whooping cough",
"Wilms’ tumour",
"Womb (uterus) cancer",
"Yellow fever",
"Virus",
"Corona virus"
]

TABLE_NAME = "\"DATA_COLLECTION\""
TABLE_ATTRIBUTES = "id_str varchar(255), created_at date, text varchar(255), \
            polarity integer, subjectivity integer, user_created_at varchar(255), user_location varchar(255), \
            user_description varchar(255), user_followers_count integer, longitude double, latitude double, \
            retweet_count integer, favorite_count integer"

OpencageApiKeys = [
    "2d711eaaa00a4b22bf81fe6cab0be109",
    "91352aa63f2e42e9949134f0dd58ec76",
    "b0a505b622c84489b4cb3fcf6a09b4cb",
    "787dac71f2e74929a77dad2f86a208b0",
    "ed59a026623e4cbfb613966c842feff9",
    "db3ec4cfc6dc46d2907100a0574320b5",
]

DEV_DATABASE_URL = "postgres://gykdutoutwmbmu:58fe951784b1417c80fd04e1adf0e21cfef7d3c5c954cba309e5f241d94e0ba2@ec2-46-137-113-157.eu-west-1.compute.amazonaws.com:5432/dc7gsfpk9oef97"
BETA_DATABASE_URL = "postgres://petznpszuzbziy:a91e1a252ce33398b9b7fffdcaaa93115364832277c7467abfd064a76d5ec486@ec2-46-137-173-221.eu-west-1.compute.amazonaws.com:5432/dc091bhi8dmmeq";